### ISSUE TITLE
Add support to start / kill external command to reprostim-videocapture

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#142]
ATM reprostim-videocapture is doing good job

For 

- #13

instead of more involved/heavier

- #139

which would still be useful for `status_command` below etc

we would need to run stimuli presentation and grabbing on the same box.  So it would make sense to accompany starting/stopping of stimuli (with QR codes etc) presentation by the same process.  Might be worth implementing as a generic platform to start/stop external processes on connect/disconnect to magewell events. ATM simply to mimic what is done with `ffmpeg`.

```yaml
external_processes:
- status_command: "xrandr"  # to execute on connect of new display or change of resolution detected
  delay: 2 # seconds to wait until running status_command to allow for possible "settling"
  regex: "^HDMI-1 connected"  # if matched -- `execute_command`
  execute_command: reprostim timesync-stimuli -t 10 --mode interval  # or via some helper with containers
  #  restart_on_exit: false # do not even bother if it dies
```

the process should be killed (similarly to what we do ffmpeg) upon disconnect.
