### ISSUE TITLE
add support for a configuration file

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#25]
I bet there is a good number of libraries to provide easy support for it if done in C/C++, choose the one you like.  Might as well be just a yaml or json file.  Then the tool would simply get `-c|--config configfile` option to specify the config file to use.

That is where/how it would be possible to specify logs location (#23) and also provide a complete ffmpeg invocation, so e.g. on a particular linux box it would be e.g. (if a yaml file)
```yaml
ffmpeg_options:
  capture: -f alsa -i hw:0 -f v4l2 ... -i /dev/video0
  output_format: mkv
```
while on OSX:
```yaml
ffmpeg_options:
  capture: -f avfoundation -i "0:1"
  output_format: avi 
```
to match your current settings.  Then those would be `format`ed into the corresponding `ffmpeg` invocation
